OutputPath: '/Users/andresperez/Documents/downloads'
LogsPath: '/Users/andresperez/Documents/logs'
SerieConfigurations:
  - SerieLink: 'https://ww3.cuevana3.me/serie/servant'
    SerieName: 'servant'
    Provider: 'cuevana'




