OutputPath: '/Users/andresperez/Documents/downloads'
AnimeConfigurations:
  - AnimeLink: 'https://www2.animeshow.tv/Tate-no-Yuusha-no-Nariagari-Season-2'
    AnimeName: 'risingShield'
    Provider: 'animeshow'

  - AnimeLink: 'https://www2.animeshow.tv/Tomodachi-Game'
    AnimeName: 'tomodachiGame'
    Provider: 'animeshow'




